name: weekly episode deployment

on:
  schedule:
    - cron:  '30 13 * * 3'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.ZEIT_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ZEIT_ORG_ID }}
          vercel-project-id: ${{ secrets.ZEIT_PROJECT_ID}}
          scope: 'specfm'
